### PR TITLE
RFC: export all symbols on windows

### PR DESCRIPTION
**Pull request by h-vetinari**
I believe the lack of this is the reason I'm getting the following failures in https://github.com/conda-forge/sentencepiece-feedstock/pull/26:
```
  Auto build dll exports
     Creating library D:/bld/sentencepiece-split_1638788302683/work/build/src/Release/sentencepiece_train_import.lib and object D:/bld/sentencepiece-split_1638788302683/work/build/src/Release/sentencepiece_train_import.exp
trainer_interface.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_unk_piece_" (?_i_give_permission_to_break_this_code_default_unk_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "public: bool __cdecl <lambda_a236839460285cbab355b426097dc600>::operator()(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_a236839460285cbab355b426097dc600>@@QEBA_NHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [D:\bld\sentencepiece-split_1638788302683\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_unk_piece_" (?_i_give_permission_to_break_this_code_default_unk_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) [D:\bld\sentencepiece-split_1638788302683\work\build\src\sentencepiece_train.vcxproj]
trainer_interface.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_bos_piece_" (?_i_give_permission_to_break_this_code_default_bos_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "public: bool __cdecl <lambda_e29d05afb1d6eeb86afbc2647f25bd32>::operator()(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum sentencepiece::ModelProto_SentencePiece_Type)const " (??R<lambda_e29d05afb1d6eeb86afbc2647f25bd32>@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ModelProto_SentencePiece_Type@sentencepiece@@@Z) [D:\bld\sentencepiece-split_1638788302683\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_bos_piece_" (?_i_give_permission_to_break_this_code_default_bos_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) [D:\bld\sentencepiece-split_1638788302683\work\build\src\sentencepiece_train.vcxproj]
trainer_interface.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_eos_piece_" (?_i_give_permission_to_break_this_code_default_eos_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "public: bool __cdecl <lambda_e29d05afb1d6eeb86afbc2647f25bd32>::operator()(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum sentencepiece::ModelProto_SentencePiece_Type)const " (??R<lambda_e29d05afb1d6eeb86afbc2647f25bd32>@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ModelProto_SentencePiece_Type@sentencepiece@@@Z) [D:\bld\sentencepiece-split_1638788302683\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_eos_piece_" (?_i_give_permission_to_break_this_code_default_eos_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) [D:\bld\sentencepiece-split_1638788302683\work\build\src\sentencepiece_train.vcxproj]
trainer_interface.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_pad_piece_" (?_i_give_permission_to_break_this_code_default_pad_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "public: bool __cdecl <lambda_e29d05afb1d6eeb86afbc2647f25bd32>::operator()(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum sentencepiece::ModelProto_SentencePiece_Type)const " (??R<lambda_e29d05afb1d6eeb86afbc2647f25bd32>@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ModelProto_SentencePiece_Type@sentencepiece@@@Z) [D:\bld\sentencepiece-split_1638788302683\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_pad_piece_" (?_i_give_permission_to_break_this_code_default_pad_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) [D:\bld\sentencepiece-split_1638788302683\work\build\src\sentencepiece_train.vcxproj]
```

For comparison, the same recipe works for linux/osx.

### CODE REVIEW

**Comment by xhochy** [comment]
> For comparison, the same recipe works for linux/osx.

Yes, because on Windows you always need to explicit export. On OSX and Linux you can choose to whether to selectively export or not.

The error above sounds more like that you need to set the flag on sentencepiece and not on protobuf. Protobuf is only part of the signature of the missing symbol, not the whole.

**Comment by h-vetinari** [comment]
> Yes, because on Windows you always need to explicit export. On OSX and Linux you can choose to whether to selectively export or not.

Is there an argument for not exporting all symbols here?

> The error above sounds more like that you need to set the flag on sentencepiece and not on protobuf. Protobuf is only part of the signature of the missing symbol, not the whole.

Yeah, I'm still debugging. But my current hypothesis was that all other problems are knock-on effects of protobuf symbols not being found.

**Comment by xhochy** [comment]
> Is there an argument for not exporting all symbols here?

Yes, the compiler may do some more optimizations if not all methods are public and also protobuf is a well-tested library; thus I would expect that missing exports would be directly discovered. Also, this option is quite a hammer, I wouldn't activate it until we have an error message that points to a symbol inside of protobuf that is missing.

**Comment by h-vetinari** [comment]
That makes sense, though two things still make me think that this is likely the cause:
* same recipe is passing on osx/linux
* sentencepiece is a google project, and (from my experience), they don't mind reaching into the internals of other google projects. For example, sentencepiece is using abseil::Flag in a way that upstream abseil explicitly disallows, so I had to undo trying that unvendor.

What do you think about adding a separate output on this feedstock with all the symbols?

**Comment by xhochy** [comment]
> sentencepiece is a google project, and (from my experience), they don't mind reaching into the internals of other google

Yes but Google mostly links statically but I don't think this is related here.

I've looked through the logs on the linked PR. None of the symbols is a direct symbol from `protobuf`, they are all related to `sentencepiece` directly. Another weird thing is that it seems to build protobuf-lite, so this feedstock here might not even be used.

**Comment by h-vetinari** [comment]
After fixing protobuf vs. protobuf-lite, the internal symbols remain what's missing:
```
  Generating Code...
  Auto build dll exports
     Creating library D:/bld/sentencepiece-split_1639015646757/work/build/src/Release/sentencepiece_import.lib and object D:/bld/sentencepiece-split_1639015646757/work/build/src/Release/sentencepiece_import.exp
sentencepiece.pb.obj : error LNK2019: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A) referenced in function "public: virtual unsigned char * __cdecl sentencepiece::SentencePieceText_SentencePiece::_InternalSerialize(unsigned char *,class google::protobuf::io::EpsCopyOutputStream *)const " (?_InternalSerialize@SentencePieceText_SentencePiece@sentencepiece@@UEBAPEAEPEAEPEAVEpsCopyOutputStream@io@protobuf@google@@@Z) [D:\bld\sentencepiece-split_1639015646757\work\build\src\sentencepiece.vcxproj]
sentencepiece_model.pb.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A) [D:\bld\sentencepiece-split_1639015646757\work\build\src\sentencepiece.vcxproj]
sentencepiece.pb.obj : error LNK2019: unresolved external symbol "struct std::atomic<bool> google::protobuf::internal::init_protobuf_defaults_state" (?init_protobuf_defaults_state@internal@protobuf@google@@3U?$atomic@_N@std@@A) referenced in function "public: virtual unsigned char * __cdecl sentencepiece::SentencePieceText_SentencePiece::_InternalSerialize(unsigned char *,class google::protobuf::io::EpsCopyOutputStream *)const " (?_InternalSerialize@SentencePieceText_SentencePiece@sentencepiece@@UEBAPEAEPEAEPEAVEpsCopyOutputStream@io@protobuf@google@@@Z) [D:\bld\sentencepiece-split_1639015646757\work\build\src\sentencepiece.vcxproj]
sentencepiece_model.pb.obj : error LNK2001: unresolved external symbol "struct std::atomic<bool> google::protobuf::internal::init_protobuf_defaults_state" (?init_protobuf_defaults_state@internal@protobuf@google@@3U?$atomic@_N@std@@A) [D:\bld\sentencepiece-split_1639015646757\work\build\src\sentencepiece.vcxproj]
D:\bld\sentencepiece-split_1639015646757\work\build\src\Release\sentencepiece.dll : fatal error LNK1120: 2 unresolved externals [D:\bld\sentencepiece-split_1639015646757\work\build\src\sentencepiece.vcxproj]
```

**Comment by xhochy** [comment]
I had a look at the first one and that should definitely be exported: https://github.com/protocolbuffers/protobuf/blob/29b3d01572d50c0e5bc0ab2eea32f9779c7576f4/src/google/protobuf/message_lite.h#L134

**Comment by xhochy** [comment]
@h-vetinari can you give https://github.com/protocolbuffers/protobuf/issues/2502#issuecomment-670628232 a try?

**Comment by xhochy** [comment]
See also for a similar patch https://github.com/hcho3/treelite-feedstock/blob/c738641eebb36ad6248c2292ed9587cb33ed34df/recipe/0001-use-dynamic-libprotobuf.patch

**Comment by h-vetinari** [comment]
Thanks, that was a great tip! :)

**Comment by h-vetinari** [comment]
@xhochy, I'd like to try if exporting all symbols fixes https://github.com/conda-forge/sentencepiece-feedstock/pull/26

How about pushing this into a `libprotobuf_dev` channel? Then I could still pull it in from there.

**Comment by xhochy** [comment]
Yes, please go ahead with that.

**Comment by h-vetinari** [comment]
OK, cool, thanks. Could you create a `dev` branch (or similar) and point this PR to it? (assuming we don't want this to go into master)

**Comment by xhochy** [comment]
Don't you want to add yourself as a maintainer here to make things simpler? I trust you doing good work 😀

**Comment by h-vetinari** [comment]
> Don't you want to add yourself as a maintainer here to make things simpler? I trust you doing good work 😀

OK: #105
